apiVersion: apps/v1
kind: Deployment
metadata:
  name: apollo-deviceprocess-gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apollo-deviceprocess-gateway
  template:
    metadata:
      labels:
        app: apollo-deviceprocess-gateway
    spec:
      serviceAccountName: apollo-deviceprocess-gateway
      containers:
      - name: gateway
        image: apollo/gateway:dev
        imagePullPolicy: IfNotPresent
        args:
        - --addr=:8080
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: apollo-deviceprocess-gateway
  namespace: default
spec:
  selector:
    app: apollo-deviceprocess-gateway
  ports:
  - name: http
    port: 8080
    targetPort: 8080
