apiVersion: v1
kind: ServiceAccount
metadata:
  name: apollo-deviceprocess-gateway
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apollo-deviceprocess-gateway-role
rules:
- apiGroups: ["azure.com"]
  resources: ["deviceprocesses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["azure.com"]
  resources: ["deviceprocesses/status"]
  verbs: ["get", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apollo-deviceprocess-gateway-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apollo-deviceprocess-gateway-role
subjects:
- kind: ServiceAccount
  name: apollo-deviceprocess-gateway
  namespace: default
