apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- gateway_service_account.yaml
- gateway_role.yaml
- gateway_role_binding.yaml
