apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apollo-deviceprocess-manager-role
rules:
- apiGroups:
  - azure.com
  resources:
  - deviceprocesses
  - deviceprocessdeployments
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - delete
- apiGroups:
  - azure.com
  resources:
  - deviceprocesses/status
  - deviceprocessdeployments/status
  verbs:
  - get
- apiGroups:
  - azure.com
  resources:
  - networkswitches
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
