apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bases/azure.com_deviceprocesses.yaml
- bases/azure.com_deviceprocessdeployments.yaml
- bases/azure.com_networkswitches.yaml
